// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/alfianbr16",
            "email": "714220048@std.ulbi.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/delete/{id}": {
            "delete": {
                "description": "Hapus data makanan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Makanan"
                ],
                "summary": "Delete Data MakananHewan.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/ins": {
            "post": {
                "description": "Input data makanan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Makanan"
                ],
                "summary": "Insert Data MakananHewan.",
                "parameters": [
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ReqMakananHewan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.MakananHewan"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/makanan": {
            "get": {
                "description": "Mengambil semua data makanan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Makanan"
                ],
                "summary": "Get All Data MakananHewan.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.MakananHewan"
                        }
                    }
                }
            }
        },
        "/makanan/{id}": {
            "get": {
                "description": "Ambil per ID data makanan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Makanan"
                ],
                "summary": "Get By ID Data MakananHewan.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.MakananHewan"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/update/{id}": {
            "put": {
                "description": "Ubah data makanan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Makanan"
                ],
                "summary": "Update Data MakananHewan.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ReqMakananHewan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.MakananHewan"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Hewan": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "jenis": {
                    "type": "string",
                    "example": "Anjing"
                },
                "ras": {
                    "type": "string",
                    "example": "Pitbull"
                },
                "umur": {
                    "type": "string",
                    "example": "8"
                }
            }
        },
        "controller.MakananHewan": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "bahan": {
                    "type": "string",
                    "example": "Daging Ikan"
                },
                "berat": {
                    "type": "string",
                    "example": "4"
                },
                "harga": {
                    "type": "string",
                    "example": "500000"
                },
                "hewan": {
                    "$ref": "#/definitions/controller.Hewan"
                },
                "jenismakanan": {
                    "type": "string",
                    "example": "Basah"
                },
                "merk": {
                    "type": "string",
                    "example": "Whiskas"
                },
                "rasa": {
                    "type": "string",
                    "example": "Tuna"
                },
                "tanggal": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-09-01T00:00:00Z"
                }
            }
        },
        "controller.ReqHewan": {
            "type": "object",
            "properties": {
                "jenis": {
                    "type": "string",
                    "example": "Anjing"
                },
                "ras": {
                    "type": "string",
                    "example": "Pitbull"
                },
                "umur": {
                    "type": "string",
                    "example": "8"
                }
            }
        },
        "controller.ReqMakananHewan": {
            "type": "object",
            "properties": {
                "bahan": {
                    "type": "string",
                    "example": "Daging Ikan"
                },
                "berat": {
                    "type": "string",
                    "example": "4"
                },
                "harga": {
                    "type": "string",
                    "example": "500000"
                },
                "hewan": {
                    "$ref": "#/definitions/controller.ReqHewan"
                },
                "jenismakanan": {
                    "type": "string",
                    "example": "Basah"
                },
                "merk": {
                    "type": "string",
                    "example": "Whiskas"
                },
                "rasa": {
                    "type": "string",
                    "example": "Tuna"
                },
                "tanggal": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-09-01T00:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "backend-tb-97f8facdbf4c.herokuapp.com",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "TES SWAGGER ULBI",
	Description:      "This is a sample swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
